### ISSUE TITLE
html

### ISSUE THREAD

**Issue by Maxisman25** [SoulGames/Website#3]
Beim Impressum ist diese zeile falsch : 79

<br><b>Vorname, Name</b>: Herzog, Luca

Das sollte eigentlich andersrum!

mfg Shadow ^^

**Comment by NoNamePro0** [comment]
Oh, Danke schön für die Fehlermeldung. Der Fehler wurde nun gefixt

[[Commit]](https://github.com/SoulGames/Website/commit/08d583df1c8fcee6e3051462cd5c30e011a795c4)
