### ISSUE TITLE
Minecraft-Names in Accounts

### ISSUE THREAD

**Issue by NoNamePro0** [SoulGames/Website#31]
_Adds in the table `accounts` the column `minecraft_name` for Minecraft Names_

ToDo: 
- [ ] **Add User Page**: Add an input box for asking the Minecraft-Name
- [ ] **Changes Page**: Show the Minecraft-Head before the Author-Name (#29) via [minotar.net](https://minotar.net/) (the Same from the `/team/index.html` Page)

_I mean, it's a Website for a Minecraft Server_
_If you want to edit or have an suggestion something, just edit my message. You don't need to add a new Post_

**Comment by StackNeverFlow** [comment]
With the new PR this feature is added.
