### ISSUE TITLE
Security issue: Login as Teammember

### ISSUE THREAD

**Issue by NoNamePro0** [SoulGames/Website#32]
_User can login as somebody. Just know the Username_

How?:
- Set Session-Cookie as Username

ToDo: 
- [ ] **Login**: Set the Password (Hash) as Cookie, too
- [ ] **Add Change**: Check the Password from Session Cookie

_If you want to edit or have an suggestion something, just edit my message. You don't need to add a new Post_

**Comment by StackNeverFlow** [comment]
Thanks for the report. I will fix it with the next pr.

**Comment by StackNeverFlow** [comment]
Please explain better, I don't see any Username saved in the PHPSESSID Cooke. May send a screenshot so that I better can understand where the error is.

**Comment by NoNamePro0** [comment]
Oh sorry,

in `admin/index.php` in line `27` is the Session set.

But the User can change/set/remove their Session-Variable.

Please add at the Login the Password (Hash) and check at, for example at `admin/addChange`, if the User has a corecttly Username and Password and is real

**Comment by StackNeverFlow** [comment]
Fixed the issue. You can reopen it, if something is wrong.

**Comment by NoNamePro0** [comment]
Oh yeah,

thats good.

But the User can set their Username and Password and is logged in.

So, please check on addBeta, addChange, addUser if the Username and Password is right.

What i mean is, get the User from the Database with Username. And check if the Password, from the User from DB, is the same from the Session Cookie.

I hope you know what i mean.

**Comment by StackNeverFlow** [comment]
But I think it's rarely, if not impossible that someone could guess the password hash of a user.

**Comment by NoNamePro0** [comment]
Yes, but everybody can set the Variable.

The Code only checks if the Varable is set. But not if it's the right from the DB.

**Comment by StackNeverFlow** [comment]
O.K. I will fix it with the next Pull Request.

**Comment by StackNeverFlow** [comment]
Fixed with the PR #35
